version: "3.8"
services:
  app:
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
      - ./logs:/wd/logs:rw
    env_file:
      - .env
    user: "${USER_ID:-1000}"