[tool.poetry]
name = "alternative-universe-generator"
version = "0.1.0"
description = ""
authors = ["sphrx <vovo4a@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
faker = "^28.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
