# ruff.toml

# Включите все правила по умолчанию
select = ["E", "F", "W", "I", "N", "D", "UP", "ANN", "S", "BLE", "FBT", "B", "C4", "T10", "DJ", "EM", "EXE", "ISC", "ICN", "INP", "PIE", "Q", "RSE", "RET", "SIM", "TID", "TCH", "ARG", "PD", "PGH", "PL", "TRY", "RUF"]

# Игнорируйте ошибки в некоторых директориях
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Игнорируйте некоторые ошибки
ignore = ["D100", "D104"]

# Позволяет неиспользуемые переменные при использовании с подчеркиванием
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Максимальная длина строки
line-length = 120

# Целевая версия Python
target-version = "py312"

[mccabe]
# Максимальная сложность функции
max-complexity = 10

[pydocstyle]
convention = "google"

[pycodestyle]
max-doc-length = 120